name: dynamic_ui_builder
description: A Flutter package to dynamically build multi-step forms from JSON.
version: 1.0.1+2
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.0
  signature: ^5.5.0
  flutter_rating_bar: ^4.0.1

flutter:
  uses-material-design: true

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

#flutter:
#  plugin:
#    platforms:
#      android:
#        package: com.support_libs.dynamicUiBuilder
#        pluginClass: dynamicUiBuilderPlugin